---
extends:
  - plugin:react/recommended
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
globals:
  __DEV__: false
  __PROD__: false
  __DEBUG__: false
  __DEBUG_NW__: false
  expect: false
plugins:
  - import
  - react
rules:
  accessor-pairs: 0
  array-bracket-spacing: [2, never]
  array-callback-return: 2
  arrow-body-style: [2, as-needed]
  arrow-parens: 0
  arrow-spacing: [2, {before: true, after: true}]
  block-scoped-var: 2
  brace-style: [2, 1tbs, {allowSingleLine: true}]
  callback-return: 0
  camelcase: [2, {properties: never}]
  comma-dangle: [1, always-multiline]
  comma-spacing: [2, {before: false, after: true}]
  comma-style: [2, last]
  complexity: [0, 11]
  computed-property-spacing: [2, never]
  consistent-return: 2
  consistent-this: 0
  constructor-super: 0
  curly: [2, multi-line]
  default-case: 2
  dot-location: 0
  dot-notation: [2, {allowKeywords: true}]
  eol-last: 2
  eqeqeq: 2
  func-names: 0
  func-style: 0
  generator-star-spacing: 0
  guard-for-in: 2
  handle-callback-err: 0
  id-blacklist: 0
  id-length: 0
  id-match: 0
  import/default: 2
  import/export: 2
  import/named: 2
  import/namespace: 2
  import/no-unresolved: [2, {commonjs: true, amd: true}]
  indent: [2, 2, {SwitchCase: 1}]
  init-declarations: 0
  jsx-quotes: [2, prefer-double]
  key-spacing: [2, {beforeColon: false, afterColon: true}]
  keyword-spacing: [2, {before: true, after: true, overrides: {return: {after: true}, throw: {after: true}, case: {after: true}}}]
  linebreak-style: 0
  lines-around-comment: 0
  max-depth: [0, 4]
  max-len: [1, 100, 2, {ignoreUrls: true}]
  max-nested-callbacks: 0
  max-params: [0, 3]
  max-statements: [0, 10]
  new-cap: 0
  new-parens: 0
  newline-after-var: 0
  newline-before-return: 0
  newline-per-chained-call: [0, {ignoreChainWithDepth: 3}]
  no-alert: 1
  no-array-constructor: 2
  no-bitwise: 0
  no-caller: 2
  no-case-declarations: 2
  no-catch-shadow: 0
  no-class-assign: 0
  no-cond-assign: [2, always]
  no-confusing-arrow: [2, {allowParens: true}]
  no-console: 0
  no-const-assign: 2
  no-constant-condition: 1
  no-continue: 0
  no-control-regex: 2
  no-debugger: 1
  no-delete-var: 2
  no-div-regex: 0
  no-dupe-args: 2
  no-dupe-keys: 2
  no-duplicate-case: 2
  no-else-return: 0
  no-empty-character-class: 2
  no-empty: 2
  no-eq-null: 0
  no-eval: 2
  no-ex-assign: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-boolean-cast: 0
  no-extra-label: 2
  no-extra-parens: [2, functions]
  no-extra-semi: 2
  no-fallthrough: 2
  no-floating-decimal: 0
  no-func-assign: 2
  no-implicit-coercion: 0
  no-implicit-globals: 0
  no-implied-eval: 2
  no-inline-comments: 0
  no-inner-declarations: 2
  no-invalid-regexp: 2
  no-invalid-this: 0
  no-irregular-whitespace: 2
  no-iterator: 2
  no-label-var: 0
  no-labels: [2, {allowLoop: false, allowSwitch: false}]
  no-lone-blocks: 2
  no-lonely-if: 0
  no-loop-func: 2
  no-mixed-requires: [0, false]
  no-mixed-spaces-and-tabs: 2
  no-multi-spaces: 2
  no-multi-str: 2
  no-multiple-empty-lines: [2, {max: 2, maxEOF: 1}]
  no-native-reassign: 2
  no-negated-in-lhs: 2
  no-nested-ternary: 2
  no-new-func: 2
  no-new-object: 2
  no-new-require: 0
  no-new-symbol: 2
  no-new-wrappers: 2
  no-new: 2
  no-obj-calls: 2
  no-octal-escape: 2
  no-octal: 2
  no-param-reassign: [2, {props: true}]
  no-path-concat: 0
  no-plusplus: 0
  no-process-env: 0
  no-process-exit: 0
  no-proto: 2
  no-redeclare: 2
  no-regex-spaces: 2
  no-restricted-globals: 0
  no-restricted-imports: 0
  no-restricted-modules: 0
  no-return-assign: 2
  no-script-url: 2
  no-self-assign: 2
  no-self-compare: 2
  no-sequences: 2
  no-shadow-restricted-names: 2
  no-shadow: 2
  no-spaced-func: 2
  no-sparse-arrays: 2
  no-sync: 0
  no-ternary: 0
  no-this-before-super: 0
  no-throw-literal: 2
  no-trailing-spaces: 2
  no-undef-init: 0
  no-undef: 2
  no-undefined: 0
  no-underscore-dangle: 0
  no-unexpected-multiline: 0
  no-unmodified-loop-condition: 0
  no-unneeded-ternary: [2, {defaultAssignment: false}]
  no-unreachable: 2
  no-unused-expressions: 2
  no-unused-labels: 2
  no-unused-vars: [2, { vars: all, args: after-used, argsIgnorePattern: "^_" }]
  no-use-before-define: 2
  no-useless-call: 0
  no-useless-constructor: 2
  no-var: 2
  no-void: 0
  no-warning-comments: [0, {terms: [todo, fixme, xxx], location: start}]
  no-whitespace-before-property: 2
  no-with: 2
  object-curly-spacing: [2, always]
  object-shorthand: [2, always]
  one-var-declaration-per-line: [2, always]
  one-var: [2, never]
  operator-assignment: 0
  operator-linebreak: 0
  padded-blocks: [2, never]
  prefer-arrow-callback: 0
  prefer-const: 2
  prefer-reflect: 0
  prefer-rest-params: 2
  prefer-spread: 0
  prefer-template: 2
  quote-props: [2, as-needed, {keywords: false, unnecessary: true, numbers: false}]
  quotes: [2, single, avoid-escape]
  radix: 2
  react/display-name: [0, {ignoreTranspilerName: false}]
  react/forbid-prop-types: [0, {forbid: [any, array, object]}]
  react/jsx-boolean-value: [2, never]
  react/jsx-closing-bracket-location: [2, line-aligned]
  react/jsx-curly-spacing: [0, never, {allowMultiline: true}]
  react/jsx-handler-names: [0, {eventHandlerPrefix: handle, eventHandlerPropPrefix: on}]
  react/jsx-indent-props: [2, 2]
  react/jsx-key: 0
  react/jsx-max-props-per-line: [0, {maximum: 1}]
  react/jsx-no-bind: [2, {ignoreRefs: true, allowArrowFunctions: true, allowBind: false}]
  react/jsx-no-duplicate-props: [0, {ignoreCase: false}]
  react/jsx-no-literals: 0
  react/jsx-no-undef: 2
  react/jsx-pascal-case: 0
  react/jsx-sort-props: [0, {ignoreCase: false, callbacksLast: false}]
  react/jsx-space-before-closing: [2, always]
  react/jsx-uses-react: [2, {pragma: React}]
  react/jsx-uses-vars: 2
  react/no-danger: 0
  react/no-deprecated: [1, {react: 0.14.0}]
  react/no-did-mount-set-state: [2, allow-in-func]
  react/no-did-update-set-state: [2, allow-in-func]
  react/no-direct-mutation-state: 0
  react/no-is-mounted: 2
  react/no-multi-comp: [2, {ignoreStateless: true}]
  react/no-set-state: 0
  react/no-string-refs: 0
  react/no-unknown-property: 2
  react/prefer-es6-class: [2, always]
  react/prefer-stateless-function: 2
  react/prop-types: [2, {ignore: [], customValidators: []}]
  react/react-in-jsx-scope: 2
  react/require-extension: [0, {extensions: [.jsx]}]
  react/self-closing-comp: 2
  react/sort-comp: [2, {order: [static-methods, lifecycle, /^on.+$/, '/^(get|set)(?!(InitialState$|DefaultProps$|ChildContext$)).+$/', everything-else, /^render.+$/, render]}]
  react/sort-prop-types: [0, {ignoreCase: false, callbacksLast: false}]
  react/wrap-multilines: [2, {declaration: true, assignment: true, return: true}]
  require-yield: 0
  semi-spacing: [2, {before: false, after: true}]
  semi: [2, never]
  sort-imports: 0
  sort-vars: 0
  space-before-blocks: 2
  space-before-function-paren: [2, {anonymous: always, named: never}]
  space-in-parens: [2, never]
  space-infix-ops: 2
  space-unary-ops: 0
  spaced-comment: [2, always, {exceptions: ['-', +], markers: ['=', '!']}]
  strict: 0
  template-curly-spacing: 2
  use-isnan: 2
  valid-jsdoc: 0
  valid-typeof: 2
  vars-on-top: 2
  wrap-iife: [2, outside]
  wrap-regex: 0
  yield-star-spacing: [2, after]
  yoda: 2
env:
  node: true
  mocha: true
