---
extends:
  - airbnb
  - plugin:react/recommended
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
globals:
  __DEV__: false
  __PROD__: false
  __DEBUG__: false
  __DEBUG_NW__: false
  expect: false
plugins:
  - import
rules:
  comma-dangle: [1, always-multiline]
  indent: [2, 2, { SwitchCase: 1 }]
  key-spacing: [2, { beforeColon: false, afterColon: true }]
  no-else-return: 0
  func-names: 0
  space-before-function-paren: [2, { anonymous: always, named: never} ]
  semi: [2, never]
  no-console: 0
  prefer-arrow-callback: 0
  strict: 0
  no-unused-vars: [2, { vars: all, args: after-used, argsIgnorePattern: "^_" }]
  arrow-body-style: [2, as-needed]
  import/no-unresolved: [2, {commonjs: true, amd: true}]
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
  max-len: [1, 100, 2, {ignoreUrls: true}]
env:
  node: true
  mocha: true
