version: '2'

services:
  web:
    container_name: planck-web
    image: jmfirth/webpack
    ports:
     - "8080:8080"
    volumes:
     - .:/app
    depends_on:
     - db
    links:
     - db
    command: webpack-dev-server --host 0.0.0.0
  db:
    container_name: planck-db
    image: planck/db:latest
    build: .
    ports:
      - "5984:5984"
